from __future__ import annotations


DEFAULT_CONTROL_HOST = "0.0.0.0"
DEFAULT_CONTROL_PORT = 41000
DEFAULT_VOICE_HOST = "0.0.0.0"
DEFAULT_VOICE_PORT = 41001
DEFAULT_DISCOVERY_PORT = DEFAULT_VOICE_PORT
DISCOVERY_PROTOCOL = "mayday-server-discovery-v1"
DISCOVERY_QUERY_PROTOCOL = "mayday-server-discovery-query-v1"
DEFAULT_SERVER_REGISTRY_BASE_URL = "http://14.206.48.12:42000"
DEFAULT_SERVER_REGISTRY_LIST_URL = f"{DEFAULT_SERVER_REGISTRY_BASE_URL}/mayday_servers.json"
DEFAULT_SERVER_REGISTRY_HEARTBEAT_URL = f"{DEFAULT_SERVER_REGISTRY_BASE_URL}/api/mayday/servers/heartbeat"
SESSION_TIMEOUT_SECONDS = 10
